export type ProjectStatus = "shipped" | "open-source" | "archived";
export type ProjectGroup = "product" | "tool" | "oss";

export type Project = {
  key: string;
  title: string;
  status: ProjectStatus;
  group: ProjectGroup;
  year: string;
  tags: string[];
  github?: string;
  live?: string;
  highlight?: boolean;
  stars?: number;
};

export const projects: Project[] = [
  {
    key: "itop",
    title: "iTOP: Inscrições TOP",
    status: "shipped",
    group: "product",
    year: "2024",
    highlight: true,
    tags: [
      "Next.js 14",
      "TypeScript",
      "tRPC",
      "Prisma",
      "MongoDB",
      "NextAuth",
      "CASL",
      "Tailwind",
      "Inngest",
      "Resend",
    ],
    github: "https://github.com/tgmarinho/itop-lgnd",
    live: "https://itop-lgnd-inscricoestop.vercel.app/demo",
  },
  {
    key: "unicrow",
    title: "Unicrow",
    status: "shipped",
    group: "product",
    year: "2023",
    highlight: true,
    tags: ["TypeScript", "Ethereum", "Smart Contracts", "GraphQL", "Node.js"],
    github: "https://github.com/unicrowio",
    live: "https://unicrow.io",
  },
  {
    key: "pi-tg",
    title: "Pi: AI Agent Toolkit",
    status: "open-source",
    group: "product",
    year: "2026",
    highlight: true,
    tags: [
      "TypeScript",
      "Monorepo",
      "AI Agents",
      "OpenAI",
      "Anthropic",
      "Google",
      "CLI",
      "React",
    ],
    github: "https://github.com/tgmarinho/pi-tg",
  },
  {
    key: "dale-carnegie",
    title: "Dale Carnegie AI Trainer",
    status: "open-source",
    group: "product",
    year: "2026",
    tags: ["Next.js 16", "TypeScript", "Vercel AI SDK", "Tailwind v4", "shadcn/ui"],
    github: "https://github.com/tgmarinho/dale-carnegie-principles",
    live: "https://dale-carnegie-principles.vercel.app",
  },
  {
    key: "canetaco",
    title: "Canetaço: e-signature SaaS",
    status: "open-source",
    group: "product",
    year: "2026",
    highlight: true,
    tags: [
      "Next.js 16",
      "TypeScript",
      "Supabase",
      "Drizzle",
      "Inngest",
      "WhatsApp API",
      "AWS SES",
      "Stripe",
      "Sentry",
    ],
    github: "https://github.com/tgmarinho/canetaco",
  },
  {
    key: "print3d",
    title: "3D Print Management System",
    status: "open-source",
    group: "product",
    year: "2026",
    highlight: true,
    tags: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Supabase",
      "Tailwind v4",
      "shadcn/ui",
      "dnd-kit",
      "PostgreSQL",
      "RLS",
      "Realtime",
      "Bun",
    ],
    github: "https://github.com/tgmarinho/3d-print-management-system",
  },
  {
    key: "agenda-editor",
    title: "Agenda Editor: custom planner covers",
    status: "open-source",
    group: "product",
    year: "2026",
    tags: [
      "Next.js",
      "React 19",
      "TypeScript",
      "tRPC",
      "Prisma",
      "PostgreSQL",
      "Fabric.js",
      "Asaas (Pix)",
      "Tailwind",
    ],
    github: "https://github.com/tgmarinho/agenda-editor",
  },
  {
    key: "ai-blog",
    title: "tgmarinhopro.com (this site)",
    status: "shipped",
    group: "product",
    year: "2026",
    tags: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Velite",
      "next-intl",
      "Tailwind v4",
    ],
    github: "https://github.com/tgmarinho/tgmarinho-ai-blog",
    live: "https://tgmarinhopro.com",
  },
  {
    key: "legendarios",
    title: "Legendários MS",
    status: "shipped",
    group: "product",
    year: "2024",
    tags: ["Next.js", "React", "TypeScript", "Tailwind", "Vercel"],
    live: "https://www.legendariosms.com/",
  },
  {
    key: "fluent-five",
    title: "Fluent5: English 5x5x5",
    status: "open-source",
    group: "tool",
    year: "2026",
    tags: ["Next.js 16", "React 19", "TypeScript", "Tailwind v4", "Supabase", "PWA"],
    github: "https://github.com/tgmarinho/fluent-five",
  },
  {
    key: "english-study",
    title: "English Study",
    status: "open-source",
    group: "tool",
    year: "2026",
    tags: ["React", "TypeScript", "Vite", "Bun"],
    github: "https://github.com/tgmarinho/english-text-audio-learn",
    live: "https://english-master-omega.vercel.app",
  },
  {
    key: "calc-rentabilidade",
    title: "Fixed Income Calculator",
    status: "open-source",
    group: "tool",
    year: "2025",
    tags: ["Next.js 15", "TypeScript", "Tailwind", "shadcn/ui", "React Query", "Zod"],
    github: "https://github.com/tgmarinho/calc-rentabilidade",
    live: "https://tgmarinho.github.io/calc-rentabilidade/",
  },
  {
    key: "investidor-calc",
    title: "Investor Calculator",
    status: "open-source",
    group: "tool",
    year: "2025",
    tags: ["Next.js 15", "TypeScript", "Tailwind", "shadcn/ui"],
    github: "https://github.com/tgmarinho/investidor-calc",
    live: "https://tgmarinho.github.io/investidor-calc/",
  },
  {
    key: "dynamicforms",
    title: "DynamicForms React",
    status: "open-source",
    group: "tool",
    year: "2025",
    tags: ["React", "TypeScript", "Vite", "shadcn/ui", "react-hook-form", "Zod"],
    github: "https://github.com/tgmarinho/dynamicforms-react",
  },
  {
    key: "ecoleta",
    title: "README-ecoleta",
    status: "open-source",
    group: "oss",
    year: "2020",
    highlight: true,
    stars: 223,
    tags: ["React", "Node.js", "React Native", "TypeScript", "README"],
    github: "https://github.com/tgmarinho/README-ecoleta",
  },
  {
    key: "gobarber",
    title: "GoBarber API",
    status: "open-source",
    group: "oss",
    year: "2021",
    stars: 44,
    tags: ["Node.js", "TypeScript", "Express", "TypeORM", "PostgreSQL", "Redis", "Jest", "SOLID"],
    github: "https://github.com/tgmarinho/gobarber-api-gostack11",
  },
  {
    key: "members",
    title: "Members",
    status: "open-source",
    group: "oss",
    year: "2021",
    stars: 39,
    tags: ["Next.js", "React", "Apollo", "GraphQL", "Hasura", "Chakra UI"],
    github: "https://github.com/tgmarinho/members",
    live: "https://members-app.vercel.app/",
  },
  {
    key: "meetapp",
    title: "Meetapp",
    status: "open-source",
    group: "oss",
    year: "2020",
    stars: 25,
    tags: ["React", "React Native", "Node.js", "Redux"],
    github: "https://github.com/tgmarinho/meetapp",
  },
  {
    key: "bmi-calc",
    title: "BMI Calculator (React Native)",
    status: "open-source",
    group: "oss",
    year: "2019",
    stars: 17,
    tags: ["React Native", "Styled Components", "React Navigation", "i18n", "Hooks"],
    github: "https://github.com/tgmarinho/BmiCalculatorRN",
    live: "https://play.google.com/store/apps/details?id=com.tgmarinho.imc",
  },
  {
    key: "be-the-hero",
    title: "Be the Hero",
    status: "open-source",
    group: "oss",
    year: "2020",
    stars: 14,
    tags: ["React", "React Native", "Node.js"],
    github: "https://github.com/tgmarinho/be-the-hero",
  },
];
